title: Mine Blog
email: your-email@domain.com
author: Olive
copyright: "Unpublished Work (cleft) 2023-{currentYear} {author}"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: ""
url: ""
favicon: /assets/favicon/favicon.ico
yat:
  date_format: "%Y %m %d"
markdown: kramdown
kmarkdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
